### ISSUE TITLE
Update events are missing the "before" in payload

### ISSUE THREAD

**Issue by flexwende** [noctarius/timescaledb-event-streamer#70]
Update events are missing the "before"-data in the payload, the "after" is present. This makes it hard to further work with the data and perform the correct update in a second database.

example output of an update event using `sink.type = 'stdout'`:

```json
{"payload":{"op":"u","after":{"ts":"2023-09-25T09:55:23.968497Z","details":"asdf"},"source":{"connector":"timescaledb-event-streamer","ts_ms":1695635729265,"snapshot":false,"db":"timescaledb","schema":"public","table":"event_table","lsn":"0/2244CB0","version":"0.10.1","name":"timescaledb","txId":975},"ts_ms":1695635729116}}
```

I am not sure if this is intended or can be enabled with a setting that I overlooked.

Versions:
- postgresql: 14
- timescaledb: 2.11.2
- timescaledb-event-streamer: 0.10.1

**Comment by noctarius** [comment]
You have to enable REPLICA IDENTITY FULL. I just don't remember if this is already merged or if you have to wait for 2.12.

**Comment by noctarius** [comment]
Yes, 2.12 includes all the necessary changes: https://github.com/timescale/timescaledb/pull/6086

Not sure if the packages are already available though. This version also includes a way to prevent decompressions / decompressions to create insert events.

**Comment by flexwende** [comment]
ok, thanks for the information :)
